<a href="https://colab.research.google.com/github/kasn-IA/maestria/blob/main/PALN_Practica_3_Estudiante.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h2><center>Ejercicio práctico semana 3 </center>

<b>Maestría</b>: Inteligencia Artificial Aplicada <br>
<b>Asignatura:</b> Procesamiento Acelerado de Lenguaje Natural <br>
<b>Profesor:</b> Edwin J. Rueda

**Bienvenidos** al ejercicio práctico de la segunda semana. A parte de las preguntas prácticas y teóricas que deberás responder, ten en cuenta lo siguiente:
- Encontrarás enlaces a documentación externa que te ayudará a resolver dudas.
- Resuelve los ejercicios de forma secuencial. Para que puedas ver el avance.
- La idea es guiarte sobre el proceso, por lo cual, encontrarás funciones pre-definidas.
    Por lo cual deberás colocar el código faltante dentro de las etiquetas especificadas.
- Encontrarás una salida esperada en cada celda para que tengas una guía. (Ten en cuenta que una vez ejecutada la celda, esta salida desaparecera).

### Dataset

Para este ejercicio práctico utilizaremos una fracción del dataset de MeLi. El dataset cuenta con 60k registros, los cuales hacen referencia al título de un producto y a su respectiva categoria. El objetivo del entregable es realizar un procesamiento del conjunto de datos con los métodos vistos en clase. Finalmente, veremos como se reduce la dimensionalidad y que tokens se vuelven más relevantes.

El dataset cuenta con la siguiente información:

    - title: Descripción del titúlo del producto
    - category: Categoria a la cual pertenece el producto

link del dataset: https://drive.google.com/file/d/1ivgFoL4HXwmc0u9n-rPR5c5U5lt5_Eds/view?usp=sharing

In [1]:
import pandas as pd
from time import time
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
import csv
import gdown

data = pd.read_csv("./filter_data.csv", index_col=0)
print(data.shape)
data.head()

(60000, 2)

,title,category
0,Campera Ls2 Hombre Discovery Black Solo En Mg ...,MOTORCYCLE_JACKETS
1,Peine Beiyuan 13 Dientes,COMBS
2,Collar Arranque Fiat Palio Siena Strada Pin Fi...,IGNITION_SWITCH_ACTUATORS
3,Lampara Compatible Benq Ms517f Por Pedido,PROJECTOR_LAMPS
4,Canilla Doble Esférico Riego Prog Lavarropa Fv...,IRRIGATION_VALVES

### Ejercicio 1

Crear una función que dada una lista de categorías y una sentencia perteneciente a una de las categorías de entrada, retorne como salida la categoría que tiene mas probabilidad.

**Nota:** Para este ejercicio usaremos el modelo [*RoBERTa*](https://huggingface.co/FacebookAI/roberta-large-mnli)

In [3]:
from transformers import pipeline
classifier = pipeline('zero-shot-classification', model='roberta-large-mnli')

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/688 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.43G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/393 [00:00<?, ?it/s]

RobertaForSequenceClassification LOAD REPORT from: roberta-large-mnli
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.bias   | UNEXPECTED |  |
roberta.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
def predict_category(categories, sentence):
  """
  categories: lista de categorías
  sentence: sentencia a clasificar
  return: probabilidad, categoria
  """
  ### TU CODIGO AQUÍ ###
  # El modelo RoBERTa ya está cargado en la variable 'classifier'
  # Realizamos la clasificación zero-shot
  result = classifier(sentence, categories)

  # El pipeline devuelve 'labels' y 'scores' ordenados de mayor a menor probabilidad
  probabilidad = result['scores'][0]
  categoria = result['labels'][0]

  return probabilidad, categoria
  ######################

# Ejemplo de uso solicitado en el notebook
print("------- Ejemplo de uso ---------")
cats = ["frutas", "carros", "motos", "cocina"]
sent = "el banano y la manzana están en descuento"
res_prob, res_cat = predict_category(cats, sent)
print(f"Sentence: {sent} \nOutput: ({res_prob}, '{res_cat}')")

------- Ejemplo de uso ---------
Sentence: el banano y la manzana están en descuento
Output: (0.3423751890659332, 'frutas')

Para fines de prueba, obtendremos un subconjunto de datos para predecir su categoría.

### Ejercicio 2
Obtener un subconjunto de datos en base a una lista de indices de tamaño 100. Para esto, debes completar el siguiente código, para que a partir de una lista de 100 posiciones generadas de forma aleatoria, generarar un dataset en base a las 100 posiciones.

In [5]:
np.random.seed(42) # Mantener la semilla para reproducibilidad

# 1. Generamos una lista de 100 índices aleatorios del dataset original
indexs = np.random.choice(data.index, 100, replace=False)

def get_subdata(indexs, data):
  """
  indexs: lista de indices a filtrar en el conjunto data
  data: dataset
  return: subconjunto de datos (reset index)
  """
  ### TU CODIGO AQUÍ ###
  # Seleccionamos las filas indicadas y reiniciamos el índice (reset index)
  sub_df = data.loc[indexs].reset_index(drop=True)
  return sub_df
  ######################

# Creamos el dataset de prueba de 100 registros
subdata = get_subdata(indexs, data)
subdata.head()

,title,category
0,Compresor Aire Kushiro 100 Litros 4hp Bicilind...,AIR_COMPRESSORS
1,Auto A Bateria Mini Cooper Kiddy. Arcoiris,POWERED_RIDE_ON_TOYS
2,Shampoo 1 Color Stay Protector Cabello Pintado...,HAIR_SHAMPOOS_AND_CONDITIONERS
3,Disco Turbo Diamantado Hormigon Ceramica Patro...,CUT_OFF_AND_GRINDING_WHEELS
4,Bateria Pearl Export 22/10/12/14 Exl725p Envio...,DRUMS

#### Ejercicio 4
Predicción en el subcojunto:
- Con la función creada en el **Ejercicio 1**. Realiza la predicción de la categoría de cada título en el subconjunto de datos.
- Utilizaremos como categorías solo las que se encuentran dentro del subconjunto de datos, para que el modelo sea mas rápido. (En un entorno ideal se deberían usar todas las categorías)
- En base a la métrica [balanced accuracy score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.balanced_accuracy_score.html), calcular el *accuracy* obtenido por *RoBERTa* sobre el subconjunto de datos.

In [6]:
from sklearn.metrics import balanced_accuracy_score

# 1. Pre-procesamiento de categorías (Limpieza)
# Convertimos 'MOTORCYCLE_FENDERS' a 'motorcycle fenders' para que el modelo inglés lo entienda.
unique_cats_raw = subdata['category'].unique().tolist()
clean_cats = [cat.replace('_', ' ').lower() for cat in unique_cats_raw]

# Creamos un mapa para convertir la predicción "limpia" de vuelta a la original para el score
clean_to_orig = dict(zip(clean_cats, unique_cats_raw))

titles = subdata['title'].tolist()

print("Iniciando clasificación zero-shot con etiquetas optimizadas...")

# 2. Clasificación por lotes (Batching)
# Usamos una hypothesis_template descriptiva.
# Aunque el texto es español, una plantilla en inglés ayuda al modelo RoBERTa (inglés).
results = classifier(titles,
                     candidate_labels=clean_cats,
                     hypothesis_template="This product belongs to the category of {}",
                     batch_size=16)

# 3. Mapeo de resultados
# Extraemos la etiqueta con mayor puntaje y la convertimos al formato original (ej. MOTORCYCLE_FENDERS)
predictions_cats = [clean_to_orig[res['labels'][0]] for res in results]
true_cats = subdata['category'].tolist()

# 4. Cálculo del accuracy balanceado
accuracy = balanced_accuracy_score(true_cats, predictions_cats)

print(f"Accuracy del modelo (Zero-Shot Optimizado): {accuracy * 100:.2f} %")

Iniciando clasificación zero-shot con etiquetas optimizadas...
Accuracy del modelo (Zero-Shot Optimizado): 20.74 %

In [8]:
print(f"Accuracy del modelo: {accuracy*100} %")

Accuracy del modelo: 10.638297872340425 %

#### Pregunta 1:
¿Por qué crees que obtenemos un *accuracy* bajo, si contamos con un modelo tan robusto?

RTA:  
Aunque ROBERTA es un modelo robusto, el bajo desempeño inicial se debe a que las categorías suelen ser etiquetas técnicas específicas (ej. IRRIGATION_VALVES) que no siempre aparecen en el lenguaje natural con el que fue entrenado el modelo en cuestión.
Tomando en cuenta la pregunta perse, es Overfitting. Si ni siquiera baja la Loss, el problema es el Learning Rate o la Normalización.
Además, los títulos de productos suelen ser palabras clave sueltas y no oraciones con estructura gramatical completa.

### Ajustemos nuestro modelo! (*Fine tuning*)

Vamos a ajustar a *RoBERTa* para que aprenda un poco mas de la relación de nuestro conjunto de datos y categorías.

#### Ejercicio 5

Crea un subconjunto de entrenamiento que cuente con todos los datos, menos el subconjunto generado en el **Ejercicio 2**

*Nota:* Tomar un subconjunto de dicha muestra si es que el entrenamiento del modelo no es viable por falta de capacidad de cómputo. En la salida de la celd se tomó un subconjunto de 100 muestras.

In [ ]:
### TU CODIGO AQUÍ ###
# Excluimos los índices que usamos para el subdata de prueba
train_indices_full = data.index.difference(indexs)

# Tomamos una muestra de 100 para que el entrenamiento sea rápido en la práctica
train_subdata = data.loc[train_indices_full].sample(100, random_state=42).reset_index(drop=True)

print(f"Forma del set de entrenamiento: {train_subdata.shape}")
train_subdata.head()
######################

Forma del set de entrenamiento: (100, 2)

,title,category
0,Aspiradora Sanyo 1200w Excelente Estado Funcio...,VACUUM_CLEANERS
1,Mini Adaptador Type C a Micro Usb Calidad Gtia !,CELLPHONE_USB_AND_AUXILIARY_ADAPTERS
2,Andarin Pata Pata Maxi 2 En 1 Rondi,PUSH_AND_RIDING_TOYS
3,Válvula Expansión Contitech,CAR_AC_EXPANSION_VALVES
4,Back To The Future Universal Collectible Pin L...,BUTTON_PINS

##### Tokenizamos y creamos nuestro conjunto de datos para train y para test

In [ ]:
from transformers import AutoTokenizer
from sklearn.preprocessing import LabelEncoder

LabelEncoder = LabelEncoder()
LabelEncoder.fit(data['category'])

tokenizer = AutoTokenizer.from_pretrained("roberta-large-mnli")

train_texts = train_subdata['title'].tolist()
train_labels = train_subdata['category'].tolist()
train_labels = LabelEncoder.transform(train_labels)

test_texts = subdata['title'].tolist()
test_labels = subdata['category'].tolist()
test_labels = LabelEncoder.transform(test_labels)

train_encodings = tokenizer(train_texts, truncation=True, padding=True, max_length=32)
test_encodings = tokenizer(test_texts, truncation=True, padding=True, max_length=32)

In [ ]:
import os
os.environ["WANDB_DISABLED"] = "true"

##### Convertimos nuestro conjunto de entrenamiento a un `dataset` de `torch` para que el método `Trainer` lo entienda

In [ ]:
import torch

class TextDataset(torch.utils.data.Dataset):
    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels
    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels[idx])
        return item
    def __len__(self):
        return len(self.labels)

train_dataset = TextDataset(train_encodings, train_labels)
test_dataset = TextDataset(test_encodings, test_labels)

##### Cargamos el modelo con el número de categorías que tenemos

In [ ]:
from transformers import AutoModelForSequenceClassification, AutoConfig

num_labels = len(data['category'].unique())
config = AutoConfig.from_pretrained("roberta-large-mnli", num_labels=num_labels)

model = AutoModelForSequenceClassification.from_config(config)

##### Definimos los parámetros de entrenamiento

In [ ]:
from transformers import Trainer, TrainingArguments

training_args = TrainingArguments(
    output_dir="./resultados",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=3,
    logging_dir="./logs",
    save_strategy="epoch",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset
)

`logging_dir` is deprecated and will be removed in v5.2. Please set `TENSORBOARD_LOGGING_DIR` instead.

##### Entrenamos el modelo

In [ ]:
trainer.train()

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:775: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  super().__init__(loader)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=39, training_loss=6.856368627303686, metrics={'train_runtime': 1196.6355, 'train_samples_per_second': 0.251, 'train_steps_per_second': 0.033, 'total_flos': 17564634662400.0, 'train_loss': 6.856368627303686, 'epoch': 3.0})

##### Generar predicciones:
Para generar nuevas predicciones tenemos tener en cuenta lo siguiente:
- Tomar la sentencia de entrada y tokenizarla
- Procesar los tensores de entrada (para si está siendo ejecutado en cuda, se adapten a dicho entorno)
- Generar las predicciones:
  - En este punto, utilizaremos el método `model.eval()` para informale a `torch` que vamos a generar predicciones. Esto es muy importante ya que en modelos implementados en `torch`, las capas de `Dropout` se siguen aplicando a la salida del modelo. Por lo cual nos daría una predicción diferente para la misma sentencia.

Le decimos al modelo que vamos a generar predicciones (a evaluarlo)

In [ ]:
# 1. Informamos al modelo que entra en modo de evaluación
model.eval()

# 2. Definimos una sentencia de prueba
sentence = "bateria para computador acer"

# 3. Tokenizamos la entrada asegurando el formato correcto para el modelo
inputs = tokenizer(
    sentence,
    truncation=True,
    padding=True,
    max_length=32,
    return_tensors="pt"
)

# 4. Movemos los tensores al dispositivo donde se encuentra el modelo (CPU o GPU)
inputs = {k: v.to(model.device) for k, v in inputs.items()}

# 5. Generamos la predicción desactivando el cálculo de gradientes para mayor velocidad
with torch.no_grad():
    logits = model(**inputs).logits

# 6. Obtenemos el ID de la clase con mayor probabilidad
predicted_class_id = logits.argmax().item()

# 7. Convertimos el ID a la categoría legible y mostramos el resultado
categoria_predicha = LabelEncoder.inverse_transform([predicted_class_id])[0]

print(f"Sentencia: {sentence}")
print(f"Predicción del modelo: {categoria_predicha}")

Sentencia: bateria para computador acer
Predicción del modelo: VESTS

Tokenizamos la sentencia de entrada

In [ ]:
sentence = "bateria para computador acer"
inputs = tokenizer(sentence,
                   truncation=True,
                   padding=True,
                   max_length=32,return_tensors="pt")
print(inputs)

{'input_ids': tensor([[    0,   428,  5109,   493,  3840, 44316,  9618,  4285,   254,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

Transformamos el tensor de entrada a tensor de cpu o gpu

In [ ]:
inputs = {k: v.to(model.device) for k, v in inputs.items()}
print(inputs)

{'input_ids': tensor([[    0,   428,  5109,   493,  3840, 44316,  9618,  4285,   254,     2]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}

Generamos la predicción

In [ ]:
with torch.no_grad():  # Para que no se computen los gradientes, pues no vamos a entrenar
    logits = model(**inputs).logits
predicted_class_id = logits.argmax().item()
model.config.id2label[predicted_class_id]
print(f"Predicción: {LabelEncoder.inverse_transform([predicted_class_id])}")

Predicción: ['VESTS']

#### Ejercicio 6

Crea una función de predicción del modelo anterior para que dada una sentencia, retorne  el par de  `(probabilidad, categoria)` de las 3 categorías que obtuvieron las mayores probabilidades.

In [ ]:
def predict_top_3(sentence):
    ### TU CODIGO AQUÍ ###
    model.eval() # Modo evaluación: desactiva Dropout

    # Tokenización y envío al dispositivo correcto
    inputs = tokenizer(sentence, truncation=True, padding=True, max_length=32, return_tensors="pt")
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad(): # Inferencia sin gradientes
        logits = model(**inputs).logits

    # Convertimos logits a probabilidades
    probs = torch.nn.functional.softmax(logits, dim=-1)

    # Obtenemos los top 3
    top_probs, top_ids = torch.topk(probs, 3)

    results = []
    for i in range(3):
        p = top_probs[0][i].item()
        label = LabelEncoder.inverse_transform([top_ids[0][i].item()])[0]
        results.append((p, label))

    return results
    ######################

# Ejemplo visible
print(f"Top 3 para 'bateria acer': {predict_top_3('bateria para computador acer')}")

Top 3 para: bateria para computador acer
Probabilidad: 0.0075 -> Categoría: VESTS
Probabilidad: 0.0048 -> Categoría: COLLECTIBLE_POSTCARDS
Probabilidad: 0.0043 -> Categoría: CAMERA_CHARGERS

#### Ejercicio 7

Emplea el modelo [`hiiamsid/sentence_similarity_spanish_es`](https://huggingface.co/hiiamsid/sentence_similarity_spanish_es) basado en BERT para computar la similitud de sentencia. Y crea un clasificador de n-vecinos en base a la categoría a la que pertenecen las sentencias de los n-vecinos mas cercanos.

*Nota:* crea el clasificador, no implementes uno de la literatura.

In [ ]:
from sentence_transformers import SentenceTransformer
import numpy as np

# El modelo ya está instanciado según la celda anterior, pero nos aseguramos:
# model = SentenceTransformer('hiiamsid/sentence_similarity_spanish_es')

### TU CODIGO AQUÍ ###

class KNNClassifierManual:
    """
    Clasificador de N-vecinos programado manualmente.
    Cumple con la restricción de no usar implementaciones de la literatura.
    """
    def __init__(self, encoder_model, n_neighbors=3):
        self.encoder = encoder_model
        self.n = n_neighbors
        self.train_embeddings = None
        self.train_labels = None

    def fit(self, texts, labels):
        # Convertimos todos los títulos de entrenamiento en vectores semánticos
        print("Generando base de conocimiento (embeddings)...")
        self.train_embeddings = self.encoder.encode(texts)
        self.train_labels = np.array(labels)
        print("Modelo listo para predecir.")

    def predict(self, query_text):
        # 1. Convertir el texto de consulta en vector
        query_embedding = self.encoder.encode([query_text])[0]

        # 2. Calcular la similitud de coseno de forma manual
        # Similitud = (A · B) / (||A|| * ||B||)
        dot_product = np.dot(self.train_embeddings, query_embedding)
        norm_train = np.linalg.norm(self.train_embeddings, axis=1)
        norm_query = np.linalg.norm(query_embedding)

        # Calculamos la similitud para todos los ejemplos de entrenamiento
        similarities = dot_product / (norm_train * norm_query + 1e-9)

        # 3. Obtener los índices de los N vecinos con mayor similitud
        # argsort ordena de menor a mayor, tomamos los últimos N y los invertimos
        idx_neighbors = np.argsort(similarities)[-self.n:][::-1]

        # 4. Votación manual: obtener la categoría más frecuente entre los vecinos
        labels_neighbors = self.train_labels[idx_neighbors].tolist()
        # Encontramos la moda de la lista de etiquetas
        prediction = max(set(labels_neighbors), key=labels_neighbors.count)

        return prediction

# --- Pruebas y visualización de resultados ---

# Inicializamos el clasificador manual con el modelo solicitado y 3 vecinos
mi_knn = KNNClassifierManual(model, n_neighbors=3)

# 'Entrenamos' con los títulos y categorías de train_subdata (Ejercicio 5)
mi_knn.fit(
    train_subdata['title'].tolist(),
    train_subdata['category'].tolist()
)

# Probamos con un título del subconjunto de prueba para verificar
test_title = "bateria para notebook dell"
resultado = mi_knn.predict(test_title)

print(f"\n--- Resultado de la predicción manual ---")
print(f"Título de entrada: '{test_title}'")
print(f"Categoría asignada: {resultado}")

######################

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: hiiamsid/sentence_similarity_spanish_es
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Codificando textos de entrenamiento...
Entrenamiento completado.

Resultado de la prueba manual:
Producto: 'soporte para televisor led'
Categoría asignada: AUTOMOTIVE_CELLPHONE_AND_GPS_MOUNTS

Encuesta de Retroalimentación clase NLP:

https://docs.google.com/forms/d/e/1FAIpQLSfw-vHXAZ8zndJLUHVkAU41O7NxA8IrtDsrYqDgZDjpWZAK8Q/viewform?usp=dialog